name: beachball

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare pnpm
        uses: pnpm/action-setup@v2

      - name: Prepare Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install

      - name: Check
        run: |
          pnpm run lint

  release:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare pnpm
        uses: pnpm/action-setup@v2

      - name: Prepare Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install

      - name: Release
        env:
          GH_USER: Nek0-hinata
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_REPO: Nek0-hinata/projectS
        run: |
          git config user.email "tony1160578676@gmail.com"
          git config user.name "Nek0-hinata"
          git remote set-url origin "https://${GH_USER}:${GH_TOKEN}@github.com/${GH_REPO}.git"
